---
# Summary of Steps
# 1. Stop target database (if running)
# 2. Unmount the filesystem on target server (if mounted)
# 3. Take snapshot of the source volumes on Pure
# 4. Mount the cloned volumes on target server
# 5. Bring up the database on target server in mount mode
# 6. Change the database name using nid
# 7. Rename the directories on cloned database
# 8. Bring up the database & change filenames
#
- name: Oracle Database Refresh for Windows
  hosts: tgtwinsvr
  vars_files:
    - vars/arrays.yaml
    - vars/database.yaml 
  collections:
    - purestorage.flasharray

  gather_facts: false

  tasks:
# Set Suffix
    - set_fact:
        suffix: "ansible{{ 1000 | random }}"
      run_once: yes

# Create Oracle admin directories
    - include: tasks/create_admin.yaml
      tags: setup

# Set-up
    - include: tasks/setup.yaml
      tags: setup

# Take Snapshot of database volumes
    - include: tasks/take_snapshot2.yaml
      delegate_to: localhost

# Stop Target Database
    - include: tasks/shutdown_DB.yaml

# Unmount Target volume
    - include: tasks/offline_volume.yaml

# Copy Snapshot to target database volume
    - include: tasks/copy_volume2.yaml
      delegate_to: localhost

# Mount Target volume
    - include: tasks/online_volume.yaml

# Startup Mount Target Database
    - include: tasks/startupMount_DB.yaml
      tags: startup

# Change Database Name
    - include: tasks/nid.yaml
      tags: startup

#    - meta: end_play

# Rename target database file names
    - name: Rename Target database directories
      win_command: 'cmd.exe /c rename {{ item.value.sourced }} {{ item.value.targetd }}'
      args:
        chdir: "{{ tgt_dir }}"
      with_dict: "{{ dirmap }}"
    
# Rename target database file names
    - include: tasks/rendbfiles.yaml

# Delete Snapshot of database volumes
    - include: tasks/delete_snapshot2.yaml
      delegate_to: localhost
