---
# Create audit and diag directories e.g 
# C:\app\oracle\diag\rdbms\prod\prod\trace
# C:\app\oracle\admin\prod\prod\adump
#
- name: Create Source Oracle audit and diag directories
# use ansible win_file module
  win_file: 
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}\\trace"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}\\alert"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}\\incident"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}\\cdump"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ src_db }}\\{{ src_db }}\\hm"
    - "{{ tgt_ob }}\\admin\\{{ src_db }}\\adump"
    - "{{ tgt_ob }}\\admin\\{{ src_db }}\\dpdump"
    - "{{ tgt_ob }}\\admin\\{{ src_db }}\\pfile"
  tags: setup

- name: Create Target Oracle audit and diag directories
# use ansible win_file module
  win_file: 
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}\\trace"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}\\alert"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}\\incident"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}\\cdump"
    - "{{ tgt_ob }}\\diag\\rdbms\\{{ tgt_db }}\\{{ tgt_db }}\\hm"
    - "{{ tgt_ob }}\\admin\\{{ tgt_db }}\\adump"
    - "{{ tgt_ob }}\\admin\\{{ tgt_db }}\\dpdump"
    - "{{ tgt_ob }}\\admin\\{{ tgt_db }}\\pfile"
  tags: setup

