---
# Offline volumes
- name: offline target database volumes
  win_command: powershell.exe -ExecutionPolicy ByPass -File {{ tgt_dir }}\offline.ps1 
  register: out

- debug: 
   var: out.stdout_lines
   verbosity: 1
